import Head from 'next/head'
import About from './components/about'
import Header from './components/header'
import Landing from './components/landing'
import Projects from './components/projects'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ethan Galvan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='snap-y snap-mandatory h-screen overflow-y-scroll' >
        {/* HERE GOES THE IMPORTED VIEWS IN ORDER */}
        <Landing />
        <Projects />
        <About />
      </main>
    </>
  )
}
