import Head from 'next/head'
import Landing from './components/landing'
import Projects from './components/projects'
import Projects2 from './components/projects2'
import About from './components/about'
import Footer from './components/footer'

export default function Home() {
  return (
    <>
        <Head>
            <title>Ethan Galvan</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" /> 
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> 
            <link href="https://fonts.googleapis.com/css2?family=Just+Another+Hand&display=swap" rel="stylesheet" /> 
        </Head>

        <main className='snap-y snap-mandatory h-screen overflow-y-scroll' >
            {/* HERE GOES THE IMPORTED VIEWS IN ORDER */}
            <Landing />
            <Projects />
            <Projects2 />
            <About />
            <Footer />
        </main>
    </>
  )
}
